## Numpy Arrays

In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3]

In [3]:
type(my_list)

list

In [4]:
np_lst = np.array(my_list)

In [5]:
type(np_lst)

numpy.ndarray

In [6]:
new_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
new_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(new_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Create a numpy array using the arange function that is similar to the range function in python

In [9]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### Create an array of zeros or ones

In [10]:
# One dimensional vector of floating point zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
# Two dimensional vector of floating point zeros 5 rows, 3 columns
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones((2, 7))

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [13]:
# Numpy returns back things as floating point numbers by default in order to preserve precision

In [14]:
# The linspace function returns an array of equally spaced specified numbers between two defined start and stop numbers
# Here, 0 is the starting point, 10 is the end point, and 3 is the number of numbers you want within the specified start and stop numbers.
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [15]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

## Random Library in Numpy
#### Numpy has its own built-in random library

In [16]:
# The rand module returns a series of random numbers between 0 and 1, 0 inclusive and 1 exclusive
np.random.rand(1)

array([0.77480567])

In [17]:
np.random.rand(3, 2)

array([[0.50407498, 0.42277497],
       [0.61451122, 0.28780365],
       [0.50401348, 0.78603218]])

In [18]:
np.random.randint(0, 101, 10)

array([90, 82, 53, 74, 56, 29, 12, 90, 16, 61], dtype=int32)

In [19]:
np.random.randint(0, 101, (4, 5))

array([[14, 71, 29, 54, 58],
       [30, 11, 79, 87, 62],
       [63, 83, 23, 49, 87],
       [76, 20, 81, 41, 68]], dtype=int32)

In [20]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [21]:
np.random.seed(0)
np.random.rand(4)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318])

### Numpy Arrays

In [22]:
arr = np.arange(0,11)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
# Accessing an element using its index
arr[5]

np.int64(5)

In [25]:
arr[1:5]

array([1, 2, 3, 4])

In [26]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [27]:
arr[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

#### Broadcasting: This allows you to assign a value to multiple elements in an array

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr[0:4] = 75

In [30]:
arr

array([75, 75, 75, 75,  4,  5,  6,  7,  8,  9, 10])

In [31]:
slice_of_arr = arr[:5]

In [32]:
slice_of_arr

array([75, 75, 75, 75,  4])

In [33]:
slice_of_arr[:] = 100

In [34]:
slice_of_arr

array([100, 100, 100, 100, 100])

In [35]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [36]:
# To manipulate a part of an array without affecting the original array, we'll use the .copy method
arr_copy = arr.copy()

In [37]:
arr_copy[5:] = 300

In [38]:
arr_copy

array([100, 100, 100, 100, 100, 300, 300, 300, 300, 300, 300])

In [39]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

### 2-D Arrays

In [40]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [41]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr_2d[0][1]

np.int64(2)

In [43]:
arr_2d.shape

(3, 3)

In [44]:
# Another way to access an element in a 2-dimensional array is to separate the row and column indexes by a comma in the same set of square brackets
arr_2d[0, 2]

np.int64(3)

#### Slicing 2-dimensional arrays

In [45]:
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
# The first number signifies the row, and the second, the column
arr_2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [47]:
arr = np.arange(1, 11)

In [48]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
# Checking for conditions in an array
# To check for any numbers greater than 4:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [50]:
# To return the values instead of the boolean array when you check for the condition
bool_arr = arr > 4

In [51]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [52]:
# It returns all the True values
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [53]:
arr[arr < 8]

array([1, 2, 3, 4, 5, 6, 7])

### Numpy Operations

In [54]:
arr = np.arange(0, 10)

In [55]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [57]:
arr - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [58]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [59]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [60]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [61]:
arr / arr

C:\Users\inioluwa.daniel\AppData\Local\Temp\ipykernel_21276\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [62]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [63]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [64]:
np.log(arr)

C:\Users\inioluwa.daniel\AppData\Local\Temp\ipykernel_21276\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [65]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr.sum()

np.int64(45)

In [67]:
arr.max()

np.int64(9)

In [68]:
arr.min()

np.int64(0)

In [69]:
arr.mean()

np.float64(4.5)

In [70]:
arr.var()

np.float64(8.25)

In [71]:
arr.std()

np.float64(2.8722813232690143)

In [72]:
# Reshape arrays
arr2d = np.arange(0, 25).reshape(5, 5)

In [73]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [74]:
arr2d.shape

(5, 5)

In [75]:
arr2d.sum()

np.int64(300)

In [76]:
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [78]:
# Axis 0 is the rows. (It returns the sum of the columns)
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])